### ISSUE TITLE
npm install/ require issue

### ISSUE THREAD

**Issue by stephsachrajda** [softwarefx/jChartFX#1]
installed through 

```
npm install --save jchartfx

var cfx = require('jchartfx');
```

results in 

```
'TypeError: Arguments to path.resolve must be strings'
```

**Comment by softwarefx** [comment]
Thank you for your interest in jChartFX

Unfortunately, for the time being jChartFX does not support node.js integration, thus we recently unpublished the npm package to avoid misleading. 

We are sorry for the inconveniences.
